name: API Automation CI

# Trigger the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 (or any version you are using)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Install dependencies and run tests
      - name: Run Maven tests
        run: mvn clean test

      # Install Allure CLI (version 2.10.0)
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.10.0/allure-2.10.0.zip
          unzip allure-2.10.0.zip -d /opt/
          sudo ln -s /opt/allure-2.10.0/bin/allure /usr/local/bin/allure
          allure --version  # Check if allure is installed successfully

      # Generate Allure report
      - name: Generate Allure report
        run: mvn allure:report

      # Publish Allure report
      - name: Publish Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
